---
version: "3.3"
services:
  salmonmd:
    image: ${IMAGE_REPO_HOST}/salmonmd:${JETPACK_VER}
    env_file:
      - ./.env
    container_name: salmonmd
    network_mode: host
    volumes:
      - ${DRIVE}:${DRIVE}
    runtime: nvidia
    restart: always
    command: >
      bash -c "cd tools && python3 /tools/training/tools/run_motion_detect_rtsp.py --fps ${FPS} '${RTSP_URL}' \"${DRIVE}\""
