---
version: "3.3"
services:
  salmonmd:
    image: salmonmd-test
    #image: ${IMAGE_REPO_HOST}/salmonmd:r32.7.1
    environment:
      - HOSTNAME
    env_file:
      - ./.env
    container_name: salmonmd
    network_mode: host
    volumes:
      - /mnt/pi-drive:/mnt/pi-drive
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: always
    command: >
      bash -c "cd tools &&
               python3 /tools/training/tools/run_motion_detect_rtsp.py '${RTSP_URL}' \"/mnt/pi-drive/$${HOSTNAME}\""
