version: '3.8'

services:
  salmon_counter:
    image: ${IMAGE_REPO_HOST}/salmoncounter:${TAG}
    container_name: salmon_counter
    environment:
      - HOSTNAME
    env_file:
      - ./.env
    user: ${HOST_UID}:${HOST_GID}
    volumes:
      - ${DRIVE}:/app/drive
      - /home/${USERNAME}/config:/app/config
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    network_mode: host
    runtime: nvidia
    restart: always
    working_dir: /app
    command: bash -c 'export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libstdc++.so.6; python3 watcher.py ${TEST} --weights ${WEIGHTS}'

