version: '3.8'

services:
  salmon_counter:
    image: ${IMAGE_REPO_HOST}/salmoncounter:${TAG}
    container_name: salmon_counter
    environment:
      - HOSTNAME
    env_file:
      - ./.env
    volumes:
      - ${DRIVE}:/app/drive
      - ./config:/app/config
    network_mode: host
    runtime: nvidia
    restart: always
    working_dir: /app
    command: python3 watcher.py ${TEST} --weights ${WEIGHTS}

