---
version: "3.3"
services:
  syncing:
    image: rclone/rclone
    env_file:
      - ./.env
    container_name: syncing
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USER}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    restart: always
    entrypoint: /bin/sh
    command: |
      -c 'rclone copy --bwlimit=0 --buffer-size=128M --checkers=8 --transfers=8 --include "/${SITE_NAME}/*/motion_vids/**" ${DRIVE}/${ORGID} aws:${BUCKET}/${ORGID} --config /config/rclone/rclone.conf --log-level INFO; echo "Waiting 5 min"; sleep 300'
  syncing-detects:
    image: rclone/rclone
    env_file:
      - ./.env
    container_name: syncing-detects
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USER}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    restart: always
    entrypoint: /bin/sh
    command: |
      -c 'rclone copy --bwlimit=0 --buffer-size=128M --checkers=8 --transfers=8 --include "/${SITE_NAME}/*/detections/**" ${DRIVE}/${ORGID} aws:${BUCKET}/${ORGID} --config /config/rclone/rclone.conf --log-level INFO; echo "Waiting 5 min"; sleep 300'
  syncing-counts:
    image: rclone/rclone
    env_file:
      - ./.env
    container_name: syncing-counts
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USER}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    restart: always
    entrypoint: /bin/sh
    command: |
      -c 'rclone copy --bwlimit=0 --buffer-size=128M --checkers=8 --transfers=2 --include "/${SITE_NAME}/*/counts/**" ${DRIVE}/${ORGID} aws:${BUCKET}/${ORGID} --config /config/rclone/rclone.conf --log-level INFO; echo "Waiting 5 min"; sleep 300'
  salmonmd-jetson-0:
    image: ${IMAGE_REPO_HOST}/salmonmd:${TAG}
    environment:
      - HOSTNAME
    env_file:
      - ./.env
    container_name: salmonmd-jetson-0
    network_mode: host
    privileged: true
    volumes:
      - ${DRIVE}:${DRIVE}
    restart: always
    command: >
      bash -c "python3 training/tools/run_motion_detect_rtsp.py ${FLAGS} ${DEVICE_ID_0} --fps ${FPS} '${RTSP_URL_0}' \"${DRIVE}\""
  salmonmd-jetson-1:
    image: ${IMAGE_REPO_HOST}/salmonmd:${TAG}
    environment:
      - HOSTNAME
    env_file:
      - ./.env
    container_name: salmonmd-jetson-1
    network_mode: host
    privileged: true
    volumes:
      - ${DRIVE}:${DRIVE}
    restart: always
    command: >
      bash -c "python3 training/tools/run_motion_detect_rtsp.py ${FLAGS} ${DEVICE_ID_1} --fps ${FPS} '${RTSP_URL_1}' \"${DRIVE}\""
