---
version: "3.3"
services:
  syncing:
    image: rclone/rclone
    env_file:
      - ./.env
    container_name: syncing
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USER}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    restart: always
    entrypoint: /bin/sh
    command: |
      -c 'rclone copy --bwlimit=0 --buffer-size=128M --checkers=8 --transfers=8 --exclude "cont_vids/**" ${DRIVE}/${ORGID} aws:${BUCKET}/${ORGID} --config /config/rclone/rclone.conf --log-level INFO; sleep 300'
  salmonmd-jetson-0:
    image: salmonmd
    environment:
      - HOSTNAME
    env_file:
      - ./.env
    container_name: salmonmd-jetson-0
    network_mode: host
    volumes:
      - ${DRIVE}:${DRIVE}
    restart: always
    command: >
      bash -c "cd tools && python3 /tools/training/tools/run_motion_detect_rtsp.py ${ORIN} ${RASPI} ${TEST} --fps ${FPS} '${RTSP_URL}' \"${DRIVE}\""
