---
version: "3.3"
services:
  syncing:
    image: rclone/rclone
    env_file:
      - ./.env
    container_name: syncing
    volumes:
      - ${DRIVE}:${DRIVE}
      - /home/${USER}/.config/rclone/rclone.conf:/config/rclone/rclone.conf
    restart: always
    entrypoint: /bin/sh
    command: |
      -c 'rclone copy --bwlimit=0 --buffer-size=128M --checkers=32 --transfers=32 --exclude "cont_vids/**" ${DRIVE}/${ORGID} aws:${BUCKET}/${ORGID} --config /config/rclone/rclone.conf --log-level INFO; sleep 300'
