---
version: "3.3"
services:
  tailscale-oauth:
    image: tailscale/tailscale:latest
    container_name: tailscale-oauth
    # The name appear in Tailscale console
    environment:
      - TS_AUTHKEY=${YOURKEY}?ephemeral=false
      # Set tag name
      - TS_EXTRA_ARGS=--advertise-tags=tag:salmon-project
      - TS_STATE_DIR=/var/lib/tailscale
      # Using userspace, otherwise we can only access the Docker container
      - TS_USERSPACE=True
    volumes:
      # Path to store the Tailscale status
      - ${PWD}/tailscale-oauth/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    # Auto restart
    restart: always
    network_mode: host
  nginx-oauth-test:
    image: nginx
    network_mode: service:tailscale-oauth
